name = "Packwiz"
author = "Bùi Tạ Thái Phú"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "465d6711df609b22d06bff5183984fc6b98e8c7af4652aaf7fba21e3495e37f2"

[versions]
fabric = "0.18.1"
minecraft = "1.21.8"
